-- Use the retail_sales database
USE retail_sales;

-- Calculate total revenue generated from all sales transactions
SELECT 
    SUM(total_price) AS total_revenue
FROM cleaned_retail_sales;

-- Calculate total number of orders
SELECT 
    COUNT(order_id) AS total_orders
FROM cleaned_retail_sales;

-- Calculate average order value
SELECT 
    AVG(total_price) AS avg_order_value
FROM cleaned_retail_sales;

-- Find top 05-selling products based on quantity sold
SELECT 
    product,
    SUM(quantity) AS total_quantity_sold
FROM cleaned_retail_sales
GROUP BY product
ORDER BY total_quantity_sold DESC
LIMIT 05;

-- Calculate total revenue generated by each product category in lakhs
SELECT 
    category,
    ROUND(SUM(total_price) / 100000, 2) AS revenue_in_lakhs
FROM cleaned_retail_sales
GROUP BY category
ORDER BY revenue_in_lakhs DESC;

-- Calculate total revenue generated by each city in lakhs
SELECT 
    city,
    ROUND(SUM(total_price) / 100000, 2) AS revenue_in_lakhs
FROM cleaned_retail_sales
GROUP BY city
ORDER BY revenue_in_lakhs DESC;

-- Compare revenue generated through different sales channels
SELECT 
    sales_channel,
    ROUND(SUM(total_price) / 100000, 2) AS revenue_in_lakhs
FROM cleaned_retail_sales
GROUP BY sales_channel;

-- Analyze customer payment method preferences
SELECT 
    payment_method,
    COUNT(order_id) AS total_transactions
FROM cleaned_retail_sales
GROUP BY payment_method
ORDER BY total_transactions DESC;

-- Find top 05-performing stores based on total revenue
SELECT 
    store_id,
    ROUND(SUM(total_price) / 100000, 2) AS revenue_in_lakhs
FROM cleaned_retail_sales
GROUP BY store_id
ORDER BY revenue_in_lakhs DESC
LIMIT 05;

-- Identify top 05 peak sales hours based on total number of orders
SELECT 
    HOUR(order_time) AS sales_hour,
    COUNT(order_id) AS total_orders
FROM cleaned_retail_sales
GROUP BY sales_hour
ORDER BY total_orders DESC
LIMIT 05;

-- Identify top 3 peak sales hours based on total number of orders
SELECT 
    HOUR(order_time) AS sales_hour,
    COUNT(order_id) AS total_orders
FROM cleaned_retail_sales
GROUP BY sales_hour
ORDER BY total_orders DESC
LIMIT 3;


